src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>Home Country of the customer</description>
        <label>Home Country</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product selected by the customer</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Product Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomProductInfo_AuraController.cls
public class CustomProductInfo_AuraController {
    /* Name: fetchProductCostInfo
     * Description: Method to fetch the product costs based on the home country and product of the contact associated with the case
     * Parameters: CaseId
     * Return Type: List<Product_Cost__c>
    */
	@AuraEnabled
    public static List<Product_Cost__c> fetchProductCostInfo(String caseId){
        try {
            Case c = [SELECT Id,ContactId,Contact.Home_Country__c,Contact.Product__c FROM Case WHERE Id = :caseId];
            //Get fields of Product Cost based on field set QueryFields to have flexibility.
            List<Schema.FieldSetMember> prodCostFieldSetMembers = SObjectType.Product_Cost__c.FieldSets.QueryFields.getFields();
            String fields = '';
            for (Schema.FieldSetMember field : prodCostFieldSetMembers) {
                fields = fields + ' ' + field.getFieldPath() + ',';
            }
            String query = 'SELECT Id,' + fields.substring(0, fields.length() - 1) + ' FROM Product_Cost__c WHERE Country_Code__c = \'' + c.Contact.Home_Country__c + '\' AND Product__c = \'' + c.Contact.Product__c + '\'';
            List<Product_Cost__c> prodCosts = database.query(query);
            return prodCosts;
        }catch (Exception e){
            system.debug('Exception Occurred: '+e.getMessage()+' :::: on line: '+e.getStackTraceString());
            return new List<Product_Cost__c>();
        }
    }
}