src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>Home Country of the customer</description>
        <label>Home Country</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product selected by the customer</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Currency__c</fullName>
        <label>Cost Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Type__c</fullName>
        <label>Cost Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost Per Calendar Month</fullName>
                </value>
                <value>
                    <fullName>ATM Fee in other currencies</fullName>
                </value>
                <value>
                    <fullName>Card Replacement Cost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Product Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CustomProductInfo_AuraControllerTest.cls
@isTest
public class CustomProductInfo_AuraControllerTest {
    /* Name: TestSetup
     * Description: Method to set up test data
    */
	@TestSetup
    static void TestSetup(){
    	Contact cont = new Contact();
        cont.FirstName = 'Test';
        cont.LastName = 'User';
        cont.Home_Country__c = 'DE';
        cont.Product__c = 'Standard';
        insert cont;
        Case c = new Case();
        c.ContactId = cont.Id;
        insert c;
        Product_Cost__c pc = new Product_Cost__c();
        pc.Cost_Currency__c = 500;
        pc.Cost_Type__c = 'Cost Per Calendar Month';
        pc.Country_Code__c = 'DE';
        pc.Product__c = 'Standard';
        insert pc;
    }
    /* Name: testfetchProductCostInfo
     * Description: Method to test fetchProductCostInfo method from CustomProductInfo_AuraController class
    */
    @IsTest
    static void testfetchProductCostInfo() {
        Case c = [SELECT Id FROM Case LIMIT 1];
    	List<Product_Cost__c> pcList = CustomProductInfo_AuraController.fetchProductCostInfo(c.Id);
        system.assertEquals(1,pcList.size());
    }
}