src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Home_Country__c</fullName>
        <description>Home Country of the customer</description>
        <label>Home Country</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <description>Product selected by the customer</description>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UUID__c</fullName>
        <externalId>true</externalId>
        <label>UUID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product_Cost__c.object
<CustomObject>
    <fields>
        <fullName>Cost_Currency__c</fullName>
        <label>Cost Currency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_Type__c</fullName>
        <label>Cost Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Cost Per Calendar Month</fullName>
                </value>
                <value>
                    <fullName>ATM Fee in other currencies</fullName>
                </value>
                <value>
                    <fullName>Card Replacement Cost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Product</valueSetName>
        </valueSet>
    </fields>
    <label>Product Cost</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Product Cost Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Costs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductInfoAPITest.cls
@isTest
public class ProductInfoAPITest {
	/* Name: TestSetup
     * Description: Method to set up test data
    */
	@TestSetup
    static void TestSetup(){
        List<Contact> contacts = new List<Contact>();
    	Contact cont1 = new Contact();
        cont1.FirstName = 'Test';
        cont1.LastName = 'User';
        cont1.Home_Country__c = 'DE';
        cont1.Product__c = 'Standard';
        cont1.UUID__c = 'test123';
        contacts.add(cont1);
        Contact cont2 = new Contact();
        cont2.FirstName = 'Test';
        cont2.LastName = 'User';
        cont2.Home_Country__c = 'DE';
        cont2.Product__c = 'Black';
        cont2.UUID__c = 'test1234';
        contacts.add(cont2);
        insert contacts;
        Product_Cost__c pc = new Product_Cost__c();
        pc.Cost_Currency__c = 500;
        pc.Cost_Type__c = 'Cost Per Calendar Month';
        pc.Country_Code__c = 'DE';
        pc.Product__c = 'Standard';
        insert pc;
    }
    /* Name: testGet
     * Description: Method to test testGet method from ProductInfoAPI class when product is present
    */
    @IsTest
	static void testGet(){
		RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri ='https://cs13.salesforce.com/services/apexrest/Contact/test123';
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response = res;
		ProductInfoAPI.doGet();
	}
    
    /* Name: testGet
     * Description: Method to test testGet method from ProductInfoAPI class when no product is present
    */
    @IsTest
	static void testGetNoProduct(){
		RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri ='https://cs13.salesforce.com/services/apexrest/Contact/test1234';
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response = res;
		ProductInfoAPI.doGet();
	}
    
    /* Name: testGet
     * Description: Method to test testGet method from ProductInfoAPI class when no contact is present
    */
    @IsTest
	static void testGetNoContact(){
		RestRequest request = new RestRequest();
        RestResponse res = new RestResponse();
        request.requestUri ='https://cs13.salesforce.com/services/apexrest/Contact/test12345';
        request.httpMethod = 'GET';
        RestContext.request = request;
        RestContext.response = res;
		ProductInfoAPI.doGet();
	}
}